### ISSUE TITLE
Execute all user commands in the same shell instance

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/autorel#32]
At the moment the shell context is not preserved between the different command lines. That may surprise the user.

Example:

```yaml
hooks:
  verify:
    - mkdir test # Create test directory
    - cd test # Enter test directory
    - echo $PWD # We are NOT in the test directory. Because each line has a new shell context
```

There is no need to share a same context between different phases (verify, prepare and publish). But inside a given phase, all commands should be invoked in the same context.
