### ISSUE TITLE
A first-class search-n-replace feature

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/autorel#40]
Search and replace strings when releasing is a quite common operation.

Right now I have to:

1. Use `sed` in the prepare phase
2. Explicitly add the concerned file in the list of files to commit

It'd be nice if I had only a simple and single config step. Maybe something like:

```yaml
search_and_replace:
    - file: README.md
    - search: "version = \".*\""
    - replace: "version = \"{{version}}\""
```

And that search-n-replace step would take care of updating the file as well as commiting it.
